FROM golang:1.13 as builder

RUN go get -u google.golang.org/grpc/examples/helloworld/greeter_client
ADD main.go /go/src/main/
WORKDIR /go/src/main
RUN go build && ls 

ENTRYPOINT ["/go/src/main/main"]
